### ISSUE TITLE
WE-20 메인페이지, 드롭다운

### ISSUE THREAD

**Issue by Seojunhwan** [42Heroes/42WLE-Front#1]
## ✨ Feature Request check list

- [x] 이슈 제목: [Jira Ticket No] [feat] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 메인페이지 마크업
- 메인페이지 배우고 싶은, 할 수 있는 언어 선택 정보 전역 상태로 관리
- 언어 선택 드롭다운 컴포넌트 생성

## TODO

- [ ] recoil 사용법 배우기
- [ ] recoil atom 생성하기
- [ ] 메인페이지 마크업
- [ ] 드롭다운 컴포넌트 생성 (재사용 가능하게?)

**Comment by Seojunhwan** [comment]
지라 이슈가 있으니까 굳이 요거 쓸 이유가 없네요 ㅎㅎ;,,
